import { auth, googleProvider as GoogleAuthProvider } from "../firebase";
import { toast } from "sonner";

// Temporary stub for signInWithPopup since we removed Firebase
async function signInWithPopup(auth: any, provider: any): Promise<any> {
  console.warn("signInWithPopup is currently a stub in this environment. API Gateway OAuth should be implemented.");
  throw new Error("OAuth via API Gateway not yet implemented. Please verify your identityApi.getOAuthUrl flows.");
}

// In-memory access token cache
let cachedAccessToken: string | null = null;
let isSigningIn = false;

// Initialize scopes matching the OAuth consent
export const WORKSPACE_SCOPES = [
  "https://www.googleapis.com/auth/documents",
  "https://www.googleapis.com/auth/spreadsheets",
  "https://www.googleapis.com/auth/drive.file"
];

/**
 * Initiates standard sign-in/linking flow to obtain the Google Workspace Access Token
 */
export async function getWorkspaceToken(forcePrompt = false): Promise<string> {
  if (cachedAccessToken && !forcePrompt) {
    return cachedAccessToken;
  }

  if (isSigningIn) {
    throw new Error("Google authorization is already in progress.");
  }

  isSigningIn = true;
  try {
    const provider = new GoogleAuthProvider();
    // Add Scopes individually
    WORKSPACE_SCOPES.forEach(scope => provider.addScope(scope));
    
    // Force account selection/re-auth if requested
    provider.setCustomParameters({
      prompt: forcePrompt ? "consent select_account" : "select_account",
      access_type: "offline"
    });

    const result = await signInWithPopup(auth, provider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    
    if (!credential?.accessToken) {
      throw new Error("No Google access token received from authentication provider.");
    }

    cachedAccessToken = credential.accessToken;
    toast.success("Linked with Google Workspace!", {
      description: "Permissions for Google Docs & Sheets have been granted."
    });
    return cachedAccessToken;
  } catch (error: any) {
    console.error("Workspace integration error:", error);
    toast.error("Google Authorization Failed", {
      description: error.message || "Could not gain permission context."
    });
    throw error;
  } finally {
    isSigningIn = false;
  }
}

/**
 * Checks if the user has authenticated and we hold a token in memory
 */
export function hasWorkspaceToken(): boolean {
  return cachedAccessToken !== null;
}

/**
 * Sign out / clear token cache
 */
export function disconnectWorkspace() {
  cachedAccessToken = null;
  toast.success("Disconnected Google Workspace", {
    description: "In-memory API credentials have been cleared."
  });
}

// Google Docs Interface
export interface CreateDocInput {
  title: string;
  sections: Array<{
    heading?: string;
    body: string;
    bullets?: string[];
  }>;
}

/**
 * Creates a beautiful formatted document in Google Docs
 */
export async function createGoogleDoc(input: CreateDocInput): Promise<{ id: string; url: string }> {
  try {
    const token = await getWorkspaceToken();
    
    // Step 1: Create the empty Document
    const createResponse = await fetch("https://docs.googleapis.com/v1/documents", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        title: input.title
      })
    });

    if (!createResponse.ok) {
      const errorData = await createResponse.json();
      throw new Error(errorData.error?.message || "Failed to create document.");
    }

    const docData = await createResponse.json();
    const docId = docData.documentId;
    const docUrl = `https://docs.google.com/document/d/${docId}/edit`;

    // Step 2: Build sequential requests to populate styling and text
    const requests: any[] = [];
    
    // We append from top to bottom. To maintain correct indexing in sequential updates,
    // we can formulate it cleanly using batchUpdates, appending at the start or appending at endOfSection.
    // However, Google Docs API let us use insertText at index 1 sequentially, but we must compute current index tracking.
    // A simpler foolproof way is appending relative to end of section, or sending requests in reverse order,
    // or simply appending everything sequentially to segment 1.
    // Let's create an elegant structural message and batch-insert with subtle headings.
    
    let textBuffer = "";
    
    // Header Style Setup
    textBuffer += `${input.title.toUpperCase()}\n`;
    textBuffer += `Generated by nxclip.ai Studio — Creator Success Wing\n`;
    textBuffer += `====================================================\n\n`;

    input.sections.forEach(section => {
      if (section.heading) {
        textBuffer += `## ${section.heading.toUpperCase()} ##\n\n`;
      }
      textBuffer += `${section.body}\n\n`;
      if (section.bullets && section.bullets.length > 0) {
        section.bullets.forEach(bullet => {
          textBuffer += `  • ${bullet}\n`;
        });
        textBuffer += `\n`;
      }
      textBuffer += `----------------------------------------------------\n\n`;
    });

    requests.push({
      insertText: {
        location: { index: 1 },
        text: textBuffer
      }
    });

    // Fire batchUpdate
    const updateResponse = await fetch(`https://docs.googleapis.com/v1/documents/${docId}:batchUpdate`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ requests })
    });

    if (!updateResponse.ok) {
      console.warn("Docs batchUpdate failed, created doc is raw.");
    }

    return { id: docId, url: docUrl };
  } catch (err: any) {
    console.error("createGoogleDoc failed:", err);
    throw err;
  }
}

// Google Sheets Interface
export interface CreateSheetInput {
  title: string;
  sheets: Array<{
    name: string;
    headers: string[];
    rows: Array<Array<string | number>>;
  }>;
}

/**
 * Creates a structured metrics ledger in Google Sheets
 */
export async function createGoogleSheet(input: CreateSheetInput): Promise<{ id: string; url: string }> {
  try {
    const token = await getWorkspaceToken();

    // Step 1: Create the empty spreadsheet
    const createResponse = await fetch("https://sheets.googleapis.com/v4/spreadsheets", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        properties: {
          title: input.title
        },
        sheets: input.sheets.map(s => ({
          properties: {
            title: s.name
          }
        }))
      })
    });

    if (!createResponse.ok) {
      const errorData = await createResponse.json();
      throw new Error(errorData.error?.message || "Failed to create spreadsheet.");
    }

    const sheetData = await createResponse.json();
    const spreadsheetId = sheetData.spreadsheetId;
    const spreadsheetUrl = `https://docs.google.com/spreadsheets/d/${spreadsheetId}/edit`;

    // Step 2: Append the matrices to each created sheets
    for (const s of input.sheets) {
      const valueRange = {
        range: `'${s.name}'!A1`,
        majorDimension: "ROWS",
        values: [
          s.headers,
          ...s.rows
        ]
      };

      const appendResponse = await fetch(
        `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/'${s.name}'!A1:append?valueInputOption=USER_ENTERED`,
        {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${token}`,
            "Content-Type": "application/json"
          },
          body: JSON.stringify(valueRange)
        }
      );

      if (!appendResponse.ok) {
        console.warn(`Failed to write rows for sheet section ${s.name}`);
      }
    }

    return { id: spreadsheetId, url: spreadsheetUrl };
  } catch (err: any) {
    console.error("createGoogleSheet failed:", err);
    throw err;
  }
}
