import { useState, useEffect } from "react";
import { 
  FileSpreadsheet, 
  FileText, 
  Chrome, 
  X, 
  Check, 
  AlertCircle, 
  Loader2, 
  ArrowUpRight, 
  TrendingUp, 
  ShieldAlert,
  Sparkles,
  Link2Off,
  LogOut
} from "lucide-react";
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogDescription,
  DialogFooter 
} from "./ui/dialog";
import { Button } from "./ui/button";
import { 
  getWorkspaceToken, 
  hasWorkspaceToken, 
  disconnectWorkspace, 
  createGoogleDoc, 
  createGoogleSheet 
} from "../services/googleWorkspaceService";
import { toast } from "sonner";
import { motion, AnimatePresence } from "motion/react";

interface WorkspaceExportDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

export function WorkspaceExportDialog({ isOpen, onClose }: WorkspaceExportDialogProps) {
  const [isConnected, setIsConnected] = useState(false);
  const [isLinking, setIsLinking] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [exportStep, setExportStep] = useState<string>("");
  const [showConfirm, setShowConfirm] = useState<"none" | "sheets" | "docs">("none");
  const [createdResult, setCreatedResult] = useState<{ type: "sheet" | "doc"; url: string; title: string } | null>(null);

  useEffect(() => {
    if (isOpen) {
      setIsConnected(hasWorkspaceToken());
    }
  }, [isOpen]);

  const handleLinkAccount = async () => {
    setIsLinking(true);
    try {
      const token = await getWorkspaceToken(true);
      if (token) {
        setIsConnected(true);
      }
    } catch (error: any) {
      console.error(error);
    } finally {
      setIsLinking(false);
    }
  };

  const handleDisconnect = () => {
    disconnectWorkspace();
    setIsConnected(false);
    setCreatedResult(null);
  };

  const handleStartExport = (type: "sheets" | "docs") => {
    setShowConfirm(type);
  };

  const executeExportToSheets = async () => {
    setShowConfirm("none");
    setIsExporting(true);
    setCreatedResult(null);
    setExportStep("Initializing credentials...");
    
    try {
      setExportStep("Creating and spinning up spreadsheet in Drive...");
      
      const payload = {
        title: `nxClip - Creator Analytics Ledger (${new Date().toLocaleDateString()})`,
        sheets: [
          {
            name: "Overview Metrics",
            headers: ["Metric Label", "Value Metric", "Trend Delta", "Velocity Indicator"],
            rows: [
              ["Growth Rate", "+12.5%", "Upward Trend", "Healthy Peak"],
              ["Total Short Clips Published", "12 clips", "Stable", "Target Met"],
              ["Dominant Platform Channel", "TikTok Gaming", "Upward Trend", "Viral Peak"],
              ["Engagement Attention Score", "3 Pending alerts", "Downward Trend", "Action Required"],
              ["Niche Hot Opportunity", "Meme Hook Hook", "Upward Trend", "High Velocity"]
            ]
          },
          {
            name: "Channel Performance Breakdown",
            headers: ["Content Form Type", "Published Qty", "Engagement Ratio", "Primary Network", "Top Clip Title", "Viral Delta"],
            rows: [
              ["Gaming Clips", 5, "9.4%", "TikTok", "Epic Valorant Defuse clutches", "+4.2%"],
              ["AI Memes", 4, "8.1%", "Instagram Reels", "Cs2 smoke tutorial gone wrong", "+2.1%"],
              ["Studio Static Images", 3, "6.7%", "Instagram Threads", "Minecraft bento build guide", "-0.5%"]
            ]
          }
        ]
      };

      const result = await createGoogleSheet(payload);
      
      setExportStep("Writing analytics ledger cells... OK");
      toast.success("Successfully exported to Google Sheets!");
      setCreatedResult({
        type: "sheet",
        url: result.url,
        title: payload.title
      });
    } catch (err: any) {
      console.error(err);
      toast.error("Export to Sheets Failed", {
        description: err.message || "An error occurred while creating your spreadsheet."
      });
    } finally {
      setIsExporting(false);
      setExportStep("");
    }
  };

  const executeExportToDocs = async () => {
    setShowConfirm("none");
    setIsExporting(true);
    setCreatedResult(null);
    setExportStep("Initializing Google Docs service...");

    try {
      setExportStep("Provisioning custom digital advice document...");

      const docPayload = {
        title: `nxClip AI Coaching Session - ${new Date().toLocaleDateString()}`,
        sections: [
          {
            heading: "Executive Creator Intent Summary",
            body: "This professional documentation outline summarizes custom niches, gaming telemetry, stream highlights, and key algorithmic growth drivers generated by nxClip.ai for your creator channel. Use these guidelines to maximize watch-time and trigger short-form video feed recommendations."
          },
          {
            heading: "Algorithm Growth Drivers & Directives",
            body: "Based on our AI video assessments, short-form recommendations on TikTok and Instagram favour high pacing and early attention hooks. Keep your watch retention metrics high by executing these exact patterns:",
            bullets: [
              "Shorten gaming clip entry hooks to under 1.6 seconds. Play highest emotional peaks first.",
              "Inject stylized caption memes using custom typography to retain viewer interest on mobile muted devices.",
              "Integrate dynamic progress sliders on screen for viewer navigation pacing."
            ]
          },
          {
            heading: "Suggested High-Performance Gaming Niches",
            body: "Our models recommend prioritizing gaming highlights within competitive shooter streams and sandbox guides for maximum viewer share:",
            bullets: [
              "Valorant Clutches (Short clips of clutch matches with high conversational overlay)",
              "Counter-Strike 2 Smoke Tactics (Tutorial memes with extreme edit pacing)",
              "Minecraft Cozy Bento Architecture (Short timelapse overlays with lo-fi soundscapes)"
            ]
          }
        ]
      };

      const result = await createGoogleDoc(docPayload);

      setExportStep("Formatting typography style and headings... OK");
      toast.success("Successfully exported to Google Docs!");
      setCreatedResult({
        type: "doc",
        url: result.url,
        title: docPayload.title
      });
    } catch (err: any) {
      console.error(err);
      toast.error("Export to Docs Failed", {
        description: err.message || "An error occurred while creating your Google Document."
      });
    } finally {
      setIsExporting(false);
      setExportStep("");
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent id="workspace_dialog_doc_sheets" className="glass border border-white/10 max-w-[480px] bg-background text-foreground shadow-2xl p-6 rounded-2xl">
        <DialogHeader className="text-start relative">
          <DialogTitle className="text-xl font-display font-black tracking-tight text-foreground flex items-center gap-2">
            <Chrome className="size-5 text-primary" />
            Google Workspace Hub
          </DialogTitle>
          <DialogDescription className="text-xs text-muted-foreground font-medium mt-1">
            Export real-time creator analytics to Google Sheets, or document dynamic AI suggestions with Google Docs with active creator permission.
          </DialogDescription>
        </DialogHeader>

        {/* Connection Management State */}
        <div className="bg-white/5 border border-white/5 rounded-xl p-4 flex items-center justify-between mt-4">
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-lg ${isConnected ? 'bg-primary/20 text-primary' : 'bg-muted text-muted-foreground'} flex items-center justify-center`}>
              <Chrome className="size-5" />
            </div>
            <div className="text-start">
              <p className="text-sm font-bold text-foreground">
                {isConnected ? "Linked to Workspace" : "Workspace Integration"}
              </p>
              <p className="text-[10px] text-muted-foreground font-semibold">
                {isConnected ? "OAuth scopes actively linked" : "Permissions required for exports"}
              </p>
            </div>
          </div>
          {isConnected ? (
            <Button size="sm" variant="ghost" onClick={handleDisconnect} className="h-8 gap-1.5 text-[10px] font-bold text-destructive hover:bg-destructive/10">
              <LogOut size={12} />
              Disconnect
            </Button>
          ) : (
            <Button size="sm" variant="brand-gradient" onClick={handleLinkAccount} disabled={isLinking} className="h-8 font-bold text-xs">
              {isLinking ? (
                <>
                  <Loader2 className="size-3 animate-spin" />
                  Linking...
                </>
              ) : (
                "Link Account"
              )}
            </Button>
          )}
        </div>

        {/* Success state box */}
        {createdResult && (
          <motion.div 
            initial={{ opacity: 0, y: -5 }}
            animate={{ opacity: 1, y: 0 }}
            className="p-4 bg-primary/10 border border-primary/20 text-primary rounded-xl text-xs font-semibold flex flex-col gap-2 mt-4 text-start"
          >
            <div className="flex items-start gap-2.5">
              <Check size={14} className="mt-0.5 shrink-0" />
              <div>
                <p className="font-bold">Export Complete!</p>
                <p className="text-[10px] text-primary/80 mt-0.5">Created: "{createdResult.title}"</p>
              </div>
            </div>
            <a 
              href={createdResult.url} 
              target="_blank" 
              referrerPolicy="no-referrer"
              rel="noreferrer" 
              className="mt-1 inline-flex items-center justify-center gap-1 bg-primary text-primary-foreground font-bold px-3 py-1.5 text-[10px] uppercase tracking-wider rounded-lg hover:bg-primary/80 transition-colors w-full"
            >
              Open in Google {createdResult.type === "sheet" ? "Sheets" : "Docs"}
              <ArrowUpRight size={12} />
            </a>
          </motion.div>
        )}

        <div className="mt-6 space-y-4">
          <p className="text-[10px] font-black uppercase text-muted-foreground tracking-wider mb-2 text-start">Available Integrations</p>
          
          {/* Action A: Export to Google Sheets */}
          <div className="flex items-center justify-between p-3 rounded-lg border border-white/5 bg-background hover:bg-white/5 transition-colors group">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-md bg-emerald-500/10 flex items-center justify-center text-emerald-500">
                <FileSpreadsheet className="size-5" />
              </div>
              <div className="text-start">
                <h5 className="text-xs font-black text-foreground">Export to Google Sheets</h5>
                <p className="text-[10px] text-muted-foreground">Ledger KPIs, platforms & graphs breakdown</p>
              </div>
            </div>
            <Button 
              size="sm" 
              variant="outline" 
              disabled={!isConnected || isExporting}
              onClick={() => handleStartExport("sheets")}
              className="h-7 px-3 text-[10px] font-black border-emerald-500/20 hover:bg-emerald-500/10 text-emerald-500 rounded-md"
            >
              Export
            </Button>
          </div>

          {/* Action B: Export to Google Docs */}
          <div className="flex items-center justify-between p-3 rounded-lg border border-white/5 bg-background hover:bg-white/5 transition-colors group">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-md bg-blue-500/10 flex items-center justify-center text-blue-500">
                <FileText className="size-5" />
              </div>
              <div className="text-start">
                <h5 className="text-xs font-black text-foreground">Export to Google Docs</h5>
                <p className="text-[10px] text-muted-foreground">AI Coaching recommendations & game logs</p>
              </div>
            </div>
            <Button 
              size="sm" 
              variant="outline" 
              disabled={!isConnected || isExporting}
              onClick={() => handleStartExport("docs")}
              className="h-7 px-3 text-[10px] font-black border-blue-500/20 hover:bg-blue-500/10 text-blue-500 rounded-md"
            >
              Export
            </Button>
          </div>
        </div>

        {/* Global Loading state spinner during operations */}
        {isExporting && (
          <div className="flex items-center gap-3 bg-muted/30 p-3.5 border border-border mt-4 rounded-xl text-start">
            <Loader2 className="size-4 animate-spin text-primary" />
            <div>
              <p className="text-[11px] font-bold text-foreground">Writing structured assets...</p>
              <p className="text-[10px] text-muted-foreground italic mt-0.5">{exportStep}</p>
            </div>
          </div>
        )}

        {/* Mutating Action Confirmation Panel */}
        <AnimatePresence>
          {showConfirm !== "none" && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="overflow-hidden mt-4 pt-4 border-t border-white/10"
            >
              <div className="p-3.5 bg-yellow-500/10 border border-yellow-500/20 rounded-xl text-start flex gap-3">
                <ShieldAlert size={18} className="text-yellow-500 shrink-0 mt-0.5" />
                <div>
                  <h6 className="text-[11px] font-black text-yellow-500 uppercase tracking-wider">Confirm Save Request</h6>
                  <p className="text-xs text-muted-foreground font-medium mt-1 leading-relaxed">
                    This active mutation adds a customized dynamic document or spreadsheet inside your Google Drive. Open files to inspect the metrics!
                  </p>
                  <div className="flex items-center gap-2 mt-3.5">
                    <Button 
                      size="sm" 
                      variant="outline" 
                      onClick={() => setShowConfirm("none")} 
                      className="h-7 text-[10px] px-3 font-semibold text-muted-foreground"
                    >
                      Cancel
                    </Button>
                    <Button 
                      size="sm" 
                      variant="brand" 
                      onClick={showConfirm === "sheets" ? executeExportToSheets : executeExportToDocs}
                      className="h-7 text-[10px] px-4 font-bold text-primary-foreground flex items-center gap-1.5"
                    >
                      <Check size={11} />
                      Confirm & Create
                    </Button>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <DialogFooter className="mt-4 pt-4 border-t border-white/5 flex items-center justify-between sm:justify-between">
          <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground font-semibold">
            <Check size={12} className="text-emerald-500" />
            Security Rules Active
          </div>
          <Button variant="ghost" size="sm" onClick={onClose} className="h-8 font-black text-xs">
            Close Panel
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
